# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
 - group: IntuneREAD
parameters:
  - name: debug
    displayName: Debug mode
    type: boolean
    default: false
  - name: confType
    displayName: Config Type
    type: string
    values:
    - config-profile
    - compliance-policy
    - script
    - remediation-script
    - filter 

pool:
  vmImage: windows-latest
  #vmImage: 'ubuntu-latest' 

stages:
- stage: validate
  displayName: Show input
  jobs:
  - job: print_input
    displayName: Print Input
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "-------------------------------"
          Write-Host "Dev Tenant id: $(TENANT_ID)"
          Write-Host "-------------------------------"
          Write-Host "Intune object type to move: ${{parameters.confType}}"
          Write-Host "Debug mode: ${{parameters.debug}}"

- script: | 
    Install-Module Microsoft.Graph -Scope AllUsers -Force
    Get-Module Microsoft.Graph -ListAvailable | fl
    $global:authToken = Get-AuthHeader -tenantId $(TENANT_ID) -clientId $(CLIENT_SECRET) -clientSecret $(CLIENT_SECRET)
    Invoke-RestMethod -Uri https://graph.microsoft.com/beta//deviceManagement/deviceConfigurations/333b23ed-8232-4b47-a397-8628715b3621 -Headers $authToken -Method GET

# - stage: getSourceObject
#   displayName: Get source object from dev
#   jobs:
#   - job: get_object_from_dev
#     displayName: Get object from dev
#     steps:
#     - task: PowerShell@2
#       inputs:
#         filePath: '$(System.DefaultWorkingDirectory)/Get-IntuneObject.ps1'
#         arguments: '-tenantId $(TENANT_ID) -clientId $(CLIENT_ID) -clientSecret $(CLIENT_SECRET) -type ${{parameters.confType}} -objectId ${{parameters.objectId}}'
#     - task: CopyFiles@2
#       displayName: "Intune object to: $(build.artifactstagingdirectory)'"
#       inputs:
#         Contents: intuneObject.json
#         TargetFolder: $(build.artifactstagingdirectory)
#         flattenFolders: true
#     - publish: ' $(build.artifactstagingdirectory)'
#       displayName: 'Publish intune config json'
#       artifact: 'package'

# - stage: publishToProd
#   displayName: Publish object to prod
#   jobs:
#   # Download artifact
#   - job: publish_to_prod
#     displayName: Publish object to prod
#     steps:
#     - task: DownloadPipelineArtifact@2
#       displayName: 'Download Pipeline Artifact'
#       inputs:
#         artifactName: 'package'

    # - task: PowerShell@2
    #   inputs:
    #     filePath: '$(System.DefaultWorkingDirectory)/Deploy-IntuneObject.ps1'
    #     arguments: '-tenantId $(ProdTenantId) -clientId $(ProdAppId) -clientSecret $(ProdAppSecret) -type ${{parameters.confType}} -path "$(Pipeline.Workspace)/intuneObject.json"'

